### ISSUE TITLE
Html code block not correct closed in doc "http interface"

### ISSUE THREAD

**Issue by yx91490** [ClickHouse/clickhouse-website-content#3]
code below document https://clickhouse.tech/docs/en/interfaces/http/#static not correct closed:

```
<http_handlers>
...
<http_handlers>
```

code links : https://github.com/ClickHouse/clickhouse-website-content/blob/c9d0c4874fbc76291aa74bf1b8ba73438bfb33bb/docs/en/interfaces/http/index.html#L229

should be :

```
<span class=nt>&lt;/http_handlers&gt;</span>
```

Same questions in other language edition.

**Comment by alexey-milovidov** [comment]
Could you please send a PR into the main repository?
https://github.com/ClickHouse/ClickHouse/tree/master/docs

**Comment by alexey-milovidov** [comment]
Ok, I've applied the changes.
